version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    container_name: jaeger
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # OTLP gRPC receiver
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    ports:
      - "4317:4317"  # OpenTelemetry gRPC receiver
      - "4318:4318"  # OpenTelemetry HTTP receiver
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    depends_on:
      jaeger:
        condition: service_healthy  # Ensures Jaeger starts first
    networks:
      - monitoring

networks:
  monitoring:  # 🚀 Using the shared network
    external: true