global:
  scrape_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
    honor_labels: true

rule_files:
  - "alert.rules.yml"